# Generated by Django 5.2.17 on 2026-09-29 09:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=180, validators=[django.core.validators.MinLengthValidator(20), django.core.validators.MaxLengthValidator(180)])),
                ('body_markdown', models.TextField()),
                ('kind', models.CharField(choices=[('article', 'Article'), ('case-study', 'Case study')], default='article', max_length=16)),
                ('status', models.CharField(choices=[('complete', 'Complete'), ('evolving', 'Evolving'), ('archived', 'Archived')], default='complete', max_length=16)),
                ('featured_rank', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)])),
                ('hero_image', models.ImageField(blank=True, upload_to='articles/%Y/%m/')),
                ('hero_alt', models.CharField(blank=True, max_length=255)),
                ('og_image', models.ImageField(blank=True, upload_to='articles/%Y/%m/')),
                ('canonical_url', models.URLField(blank=True)),
                ('is_draft', models.BooleanField(default=True)),
                ('pub_datetime', models.DateTimeField()),
                ('mod_datetime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-pub_datetime'],
            },
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('accent', models.CharField(choices=[('signal', 'Signal'), ('warm', 'Warm'), ('value', 'Value')], max_length=16)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='ArticleRelated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_links', to='content.article')),
                ('related_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_related_links', to='content.article')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='related',
            field=models.ManyToManyField(blank=True, related_name='related_to', through='content.ArticleRelated', through_fields=('article', 'related_article'), to='content.article'),
        ),
        migrations.AddField(
            model_name='article',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='content.channel'),
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('summary', models.CharField(max_length=255)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='content.article')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SeriesArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='series_membership', to='content.article')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='content.series')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='series',
            field=models.ManyToManyField(blank=True, related_name='articles', through='content.SeriesArticle', to='content.series'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='articles', to='content.tag'),
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='topics', to='content.channel')),
            ],
            options={
                'ordering': ['channel__slug', 'slug'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='primary_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='primary_articles', to='content.topic'),
        ),
        migrations.AddField(
            model_name='article',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='articles', to='content.topic'),
        ),
        migrations.AddConstraint(
            model_name='articlerelated',
            constraint=models.UniqueConstraint(fields=('article', 'related_article'), name='article_related_unique'),
        ),
        migrations.AddConstraint(
            model_name='articlerelated',
            constraint=models.UniqueConstraint(fields=('article', 'position'), name='article_related_position_unique'),
        ),
        migrations.AddConstraint(
            model_name='articlerelated',
            constraint=models.CheckConstraint(condition=models.Q(('position__gte', 1), ('position__lte', 3)), name='article_related_position_valid'),
        ),
        migrations.AddConstraint(
            model_name='articlerelated',
            constraint=models.CheckConstraint(condition=models.Q(('article', models.F('related_article')), _negated=True), name='article_related_not_self'),
        ),
        migrations.AddConstraint(
            model_name='seriesarticle',
            constraint=models.UniqueConstraint(fields=('series', 'order'), name='series_order_unique'),
        ),
        migrations.AddConstraint(
            model_name='seriesarticle',
            constraint=models.CheckConstraint(condition=models.Q(('order__gte', 1)), name='series_order_positive'),
        ),
        migrations.AddConstraint(
            model_name='article',
            constraint=models.UniqueConstraint(fields=('channel', 'slug'), name='article_channel_slug_unique'),
        ),
        migrations.AddConstraint(
            model_name='article',
            constraint=models.CheckConstraint(condition=models.Q(('featured_rank__isnull', True), models.Q(('featured_rank__gte', 1), ('featured_rank__lte', 99)), _connector='OR'), name='article_featured_rank_valid'),
        ),
    ]
